name: CI/CD

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GH_TOKEN }}
          netrc-file = $HOME/.netrc
    - name: Prepare .netrc to access other repos
      run: echo -e "machine github.com\nlogin git\npassword ${{ secrets.GH_TOKEN }}\n\nmachine api.github.com\nlogin git\npassword ${{ secrets.GH_TOKEN }}" > $HOME/.netrc && chmod 755 $HOME/.netrc
    - name: Run devShell
      run: nix develop
